#!/usr/bin/env bash
# The bash script displays information about a subdomain

print_info () {
	SUB_DOMAIN=$2
	DOMAIN=$1
	dig "$SUB_DOMAIN"."$DOMAIN" | grep -A1 "ANSWER SECTION:" | tail -1 | awk -v SUB="$SUB_DOMAIN" '{print "The subdomain " SUB " is a " $(NF-1) " record and points to " $NF}'
}

if [ $# == 1 ]
then
	print_info "$1" www
	print_info "$1" lb-01
	print_info "$1" web-01
	print_info "$1" web-02
elif [ $# == 2 ]
then
	print_info "$1" "$2"
fi
