#!/usr/bin/env bash
# The script transfers a file from our client to a server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# Accepts 4 paramters
#	1. The path to the file to be transferred.
#	2. The IP of the server we want ot transfer the file to
#	3. The username scp connects with
#	4. The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
