#!/usr/bin/env bash
# configures to nginx server to permanently redirect the /redirect_me path
sudo sed -i '/server_name _;/a \\n\tlocation = \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4i;\n\t}' /etc/nginx/sites-available/default
