#!/usr/bin/env bash
# configures to nginx server based on file 1nstall_nginx_web_server
# to permanently redirect the /redirect_me path

apt-get update
apt-get install nginx -y
# sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#replacement="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
replacement="server_name _;\n\nrewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;}"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

sudo service nginx restart
