#!/usr/bin/env bash
# configures to nginx server based on file 1nstall_nginx_web_server
# to permanently redirect the /redirect_me path

sudo apt-get update
sudo apt-get install -y nginx 

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
# echo "Hello World!" | sudo tee /var/www/html/index.html

# replacement="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
# replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

sudo service nginx restart
