#!/usr/bin/env bash
# configures to nginx server based on file 1nstall_nginx_web_server
# to permanently redirect the /redirect_me path

sudo apt-get update
sudo apt-get install -y nginx 

sudo sh -c 'echo "Hello Joshua!" > /var/www/html/index.nginx-debian.html'
# echo "Hello World!" | sudo tee /var/www/html/index.html

# replacement="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement="server_name _;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

sudo service nginx restart
