#!/usr/bin/env bash
# Install and configure haproxy as a load balancer

sudo apt-get -y update
apt-get -y install haproxy

# configure the front-end and backend servers for the load balancer
config=\
"
frontend  http-in
        bind *:80
        mode http
        default_backend webservers
backend webservers
        balance roundrobin
        server 63210-web-01 100.25.19.204:80 check
        server 63210-web-02 54.157.159.85:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restarts the haproxy load balancer
sudo service haproxy restart
