#!/usr/bin/env bash
# the script displays a list of currently running processes
#	must show all processes, for all users, including those which might not have a TTY
#	displat in a user-oriented format.
#	show process hierarchy

ps faux
