#!/usr/bin/env bash
# the scripts displays numbers from 1 to 10 but
# displays FizzBuzz if a number is multiple of 3 and 
# displays Fizz if a number is a multiple of 3
# displays Buzz if a number is a multiple of 

for i in {1..100}; do
	if (( i % 3 == 0 && i % 5 == 0 )); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
