#!/usr/bin/env bash
# Use awk to process the Apache log file, extract IP and HTTP status code, and count occurrences

awk '{ ip_count[$1" "$9]++ } END { for (i in ip_count) print ip_count[i], i }' access.log | sort -nr -k1
