#!/usr/bin/env bash
# a loop of 10 iterations that displays "Best school" but
# displays "bad luck" on the 4th iteration
# displays "good luck" on the 8th iteration

counter=1
while [ $counter -le 10 ]; do
	if [ $counter == 4 ]
	then
		echo "bad luck"
	elif [ $counter == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
