#!/usr/bin/env bash
# a loop that displays the numbers 1 to 20 but
# displays "bad luck from China" on the 4th iteration
# displays "bad luck from Japan" on the 9th iteration
# displays "bad luck from Italy" on the 17th iteration

counter=1
while [ $counter -le 20 ]; do
	echo $counter
	if [ $counter == 4 ]
	then
		echo "bad luck from China"
	elif [ $counter == 9 ]; then
		echo "bad luck from Japan"
	elif [ $counter == 17 ]; then
		echo "bad luck from Italy"
	fi
	((counter++))
done
