#!/usr/bin/env bash
# a loop that displays the numbers 1 to 20 but
# displays "bad luck from China" on the 4th iteration
# displays "bad luck from Japan" on the 9th iteration
# displays "bad luck from Italy" on the 17th iteration

counter=1
while [ $counter -le 20 ]; do
	echo $counter
	case $counter in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((counter++))
done
