#!/usr/bin/env bash
# a bash script that configures an Ubuntu server with the below requirements
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8

echo "127.0.0.2\t\t\tlocalhost\n\t\t\tfacebook.com" > ~/hosts
cp -f ~/hosts /etc/hosts
