#!/usr/bin/env bash
# fixes the container so that nginx is running as nginx user
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
